/**
 * @format
 * @flow
 *
 * Source: https://cs.wikipedia.org/wiki/Kategorie:Liter%C3%A1rn%C3%AD_%C5%BE%C3%A1nry
 */

export default [
  'Absurdní drama',
  'Antiutopie',
  'Apokalypsa',
  'Apokryf',
  'Arabeska (literatura)',
  'Autobiografie',
  'Báchorka',
  'Bajka',
  'Balada',
  'Báseň v próze',
  'Beletrie',
  'Bildungsroman',
  'Biografie',
  'Bondovka',
  'Brak (literatura)',
  'Budovatelský román',
  'Bukolický román',
  'Burleska',
  'Bylina (pověst)',
  'Cestopis',
  'Červená knihovna',
  'Četba na pokračování',
  'Činohra',
  'Črta',
  'Deník (literatura)',
  'Detektivka',
  'Detektivní román',
  'Didaktická literatura',
  'Dobrodružná literatura',
  'Drabble',
  'Drama',
  'Duma (píseň)',
  'Dvojjazyčná kniha',
  'Elegie',
  'Entrefilet',
  'Epigram',
  'Epika',
  'Epistolární román',
  'Epos',
  'Ergodická literatura',
  'Evangelium',
  'Exemplum',
  'Fabliau',
  'Fantasy',
  'Femininní žánry',
  'Filipika',
  'Filosofická povídka',
  'Fotokomiks',
  'Fraška',
  'Frenetická literatura',
  'Giallo',
  'Gotický román',
  'Groteska',
  'Hádanka',
  'Hagiografie',
  'Haiku',
  'Hard science fiction',
  'Heroikomika',
  'Historická detektivka',
  'Historický román',
  'Horor',
  'Humoreska',
  'Chansons de geste',
  'Chaucerova strofa',
  'Chronotop',
  'Chua-pen',
  'Chvalozpěv',
  'Jednoaktovka',
  'Jüe-fu',
  'Kaligram',
  'Kancóna',
  'Kasída',
  'Knížky lidového čtení',
  'Kolportážní román',
  'Komedie',
  'Komentář',
  'Komiks',
  'Kronika',
  'Kyberpunk',
  'Legenda',
  'Legenda (rozcestník)',
  'Lejch',
  'Léon Clifton',
  'Libreto',
  'Lidová slovesnost',
  'Limerik',
  'Literární kritika',
  'Literatura faktu',
  'Lovecraftovský horor',
  'Lucidář',
  'Lyrická poezie',
  'Madrigal',
  'Mester de Clerecía',
  'Mester de Juglaría',
  'Metaromán',
  'Military science fiction',
  'Modus (literární věda)',
  'Monodická lyrika',
  'Muzeum v knize',
  'Mytická fikce',
  'Mýtus',
  'Národní kronika',
  'Nordic noir',
  'Novela (literatura)',
  'Noveleta',
  'Nový román',
  'Odborná literatura',
  'Odborný text',
  'Otrokářská povídka',
  'Paměti',
  'Pamflet',
  'Panegyrik',
  'Pastorála',
  'Pašije',
  'Pitaval',
  'Poezie',
  'Pohádka',
  'Polská literární reportáž',
  'Postila',
  'Pověst',
  'Povídka',
  'Povídka filozofická',
  'Próza',
  'Průvodce (publikace)',
  'Příležitostná poezie',
  'Přísloví',
  'Psychologický román',
  'Rčení',
  'Recenze',
  'Rispet',
  'Román',
  'Román detektivní',
  'Román epistolární',
  'Román gotický',
  'Román historický',
  'Román psychologický',
  'Román rodinného života',
  'Román rytířský',
  'Román v dopisech',
  'Román veršovaný',
  'Román-řeka',
  'Romance',
  'Romaneto',
  'Rondel (báseň)',
  'Rozhlasová hra',
  'Rozhlasový dokument',
  'Rozpočítadlo',
  'Rytířský román',
  'Říkadlo',
  'Sága',
  'Sao (básně)',
  'Scénář',
  'Science fantasy',
  'Science fiction',
  'Senzační román',
  'Sestina',
  'Sidžo',
  'Soft science fiction',
  'Sonet',
  'Soudnička',
  'Space opera',
  'Speculum (žánr)',
  'Strašidelná povídka',
  'Subžánr',
  'Symposion (literatura)',
  'Š’ (básně)',
  'Tencóna',
  'Tercína',
  'Thriller',
  'Tragédie',
  'Traktát',
  'Travestie',
  'True crime',
  'Utopie',
  'Úvaha',
  'Věnec sonetů',
  'Venkovská próza',
  'Veršovaný román',
  'Villonská balada',
  'Výklad',
  'Vyprávění',
  'Weird fiction',
  'Western',
  'Zpráva',
  'Žalm',
  'Žánr',
];
