/**
 * @format
 * @flow
 */

export default [
  'knihovna',
  'nebe',
  'peklo',
  'hospoda',
  'toaleta',
  'obchod s poníky',
  'dětské hřiště',
  'parkoviště',
  'nákupní centrum',
  'kancelář',
  'škola',
  'lékárna',
  'hračkářství',
  'svatba',
  'kremace',
  'převlíkárna',
  'koupaliště',
  'bazén',
  'školka',
  'vinárna',
  'autobusová zastávka',
  'tobogán',
  'dopravní letadlo',
  'plovárna',
  'cukrárna',
  'mars',
  'mimozemská loď',
  'kavárna',
  'liščí nora',
  'krematorium',
  'rakev',
  'psí bouda',
  'atletický stadion',
  'autobus',
  'tramvaj',
  'Brno',
  'loď',
  'ponorka',
  'sklep',
  'půda',
  'kino',
  'natáčení filmu',
  'divadlo',
  'nemocnice',
  'vězení',
  'mušle',
  'pláž',
  'módní přehlídka',
  'střecha mrakodrapu',
  'metro',
  'květinářstní',
  'jatka',
  'krmelec',
  'kadibutka',
  'postel',
  'gouč',
  'park',
  'lavička v parku',
  'staveniště',
  'lékárna',
  'chirurgie',
  'kuchnyně',
  'obchod s plavky',
  'kancelář',
  'internet',
  'hnízdo',
  'na stromě',
  'dovolená',
  'pustý ostrov',
  'v cukřence',
  'nudapláž',
  'auto',
  'knihovna',
  'párty',
  'obchod s alkoholem',
  'staveniště',
  'hackerské doupě',
  'herna',
  'pšeničné pole',
  'banka',
  'sprcha',
  'koncert',
  'festival',
  'virtuálaní realita',
  'dětské hřiště',
  'domov důchodců',
];
